name: mobsfscan

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --json'
          
      - name: Save scan results
        run: mv mobsfscan.json ${{ github.workspace }}/mobsfscan.json

      - name: Format JSON
        run: cat mobsfscan.json | python -m json.tool > mobsfscan_formatted.json

      - name: Generate HTML report
        run: python generate_report.py mobsfscan_formatted.json > report.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: mobsfscan-report
          path: report.html
