name: mobsfscan

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --json --ignore=low,medium'
        id: mobsfscan

      - name: Upload report artifact
        uses: actions/upload-artifact@v2
        with:
          name: mobsfscan-report
          path: mobsfscan.json
